# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/414a87c1-5363-478e-8e71-594dcd575fce";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2D70-7495";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/16ce1bf6-73d9-47d0-a02b-8171df0ea9c9"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
